FROM ruby:2.7.2
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
# for a JS runtime
RUN apt-get install -y nodejs

ENV DIR /var/www

RUN mkdir $DIR
WORKDIR $DIR
ADD . $DIR

ENV BUNDLE_GEMFILE=$DIR/Gemfile \
BUNDLE_JOBS=2 \
BUNDLE_PATH=/bundle
