version: '3.8'

services:
  app:
    container_name: order_list_container
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: sh ./docker/scripts/start.sh
    volumes:
      - ./:/var/www
      - ./docker/app/bundle:/bundle
      - /var/www/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mail

  nginx:
    container_name: nginx_container
    image: nginx:1.19.6
    volumes:
      - ./:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=toidang.dev.local
      - NGINX_UPSTREAM=app:3000
    depends_on:
      - app

  db:
    container_name: postgres_container
    image: postgres:12.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123123}
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:6.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  mail:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
