FROM ruby:2.7.2

RUN apt-get update -qq && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev

# for a JS runtime
RUN apt-get install -y nodejs yarn

ENV DIR /var/www

RUN mkdir $DIR
WORKDIR $DIR
ADD . $DIR

RUN mkdir -p /bundle

ENV BUNDLE_GEMFILE=$DIR/Gemfile \
BUNDLE_JOBS=5 \
BUNDLE_PATH=/bundle

# Skip installing gem documentation
RUN mkdir -p /usr/local/etc \
	&& { \
		echo 'gem: "--no-document"'; \
	} >> /usr/local/etc/gemrc

RUN bundle install --gemfile=Gemfile.dev
