:concurrency: 5
:logfile: log/sidekiq.log
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [mailers, 1]
  - [default, 1]

development:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

test:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
